#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect below requirements

sudo apt-get update -y
sudo apt-get install -y nginx

echo "Holberton School" | sudo tee /var/www/html/index.html
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com/El-gibbor permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-available/default

sudo service nginx restart
