#!/usr/bin/env bash
# Nginx Installation and Page redirection
sudo apt-get update
sudo apt-get install -y nginx

echo "Holberton School" | sudo tee /var/www/html/index.html

# Page Redirection (301, Permanently)
sudo sed -i '/listen \[::\]:80 default_server;/a \\trewrite ^/redirect_me https://github.com/El-gibbor permanent;' /etc/nginx/sites-available/default
sudo nginx -t
sudo service nginx start
